organizername: GC Digital Initiatives
institution: CUNY Graduate Center
event: Graduate Center Digital Research Institute
description: "The GC Digital Research Institute (DRI) is an introduction to core digital research skills that can be applied widely to different kinds of projects. This institute is catered toward building foundational skills and will be paced accordingly to ensure those who are new will leave feeling more confident in their skills. DRI is designed for beginning learnersâ€”those who have little or no prior experience working with a programming language."
# registerlink: 'https://docs.google.com/forms/d/e/1FAIpQLSdzVhG4mC6rku7qMPc-chbqPT1sLoHBiAXWNc_yRqJzIlRTcA/viewform' 

# Name of building or site of event
venue: Online, hosted by GC Digital Fellows

sponsors: [{ name: 'GCDRI', link: 'https://gcdri.commons.gc.cuny.edu/' }]

# address of event
location: 365 5th Ave, New York, NY 10016

contact: [{ name: 'Lisa Marie Rhody', email: 'lrhody@gc.cuny.edu'}]

# Two-letter language code
language: "en"

# Start date
datestart: 2026-01-20
enddate: 2026-01-23

instructors: ["Eunah Cho", "Meha Gupta", "Anna Corbet Schlenz", "Parisa Setayesh", "Ian Williams", "Lisa Rhody", "Zach Lloyd", "Stephen Zweibel"]

workshopsuser: 'GC-DRI'
workshopsrepo: 'DRI26' 

sessions:
 - date: 2026-01-20
   time: 09:00 
   title: "Welcome to GC DRI: Introduction and Orientation"
   description: "During this introductory session, we will introduce all of the instructors and get to know one another. We will give an overview of the DHRIFT platform, which is the website we will use for each of the workshops, and we will cover how to use the features of the curriculum website. There will be time to talk about what workshops we will be covering during the coming week, explanations of what platforms we will be using for communication, and discussion about how to ask questions, troubleshoot, and learn more. By the end of this session, you should feel comfortable with the learning environment for GC DRI and know how to ask questions and get help when you need it."
 - date: 2026-01-20
   time: 10:15 
   title: "Introduction to the Command Line"
   workshop: command-line
   description: "This workshop will introduce you to the command line, a text-based interface for interacting with your computer. We will cover basic commands, file management, and navigating the file system. Specifically, we will be using a command line interface that has been integrated into DHRIFT, the website we are using for online instruction. The skills we are learning can be used with 'terminal' on Mac or GitBash on Windows computers. You will also be able to use similar syntax when you are using Unix to interact with a server. By the end of this workshop, you will know how to figure out what account you are working in, navigate through a computer's file structures using text commands, create and modify files using text commands, and search for files or strings of text using a text command. These skills are useful when you are installing software on your machine, when you are creating websites with HTML and CSS, or when you are learning how to import data when working with Python."
 - date: 2026-01-20
   time: 12:30 
   title: "Command Line Scavenger Hunt"
   workshop: command-line
   description: "This activity will provide you with an opportunity to practice your new command line skills using a scavenger hunt through directory and file structures on your computer."
 - date: 2026-01-21
   time: 09:00 
   title: "Data Literacies and Ethics"
   workshop: data-literacies
   description: "What is data? What counts as data? What are the ethical implications when working with data? How can we manage our data? These are questions we will explore throughout the workshop. Data is foundational to nearly all digital projects and often help us to understand and express our ideas and narratives. Hence, in order to do digital work, we should know how data is captured, constructed, and manipulated. We will also engage with the ethical dimensions of what it means to work with data, from collection to visualization to management."
 - date: 2026-01-21
   time: 10:45 
   title: "HTML / CSS"
   workshop: html-css
   description: "HTML (Hypertext Markup Language) is used to create and organize the content of a website. CSS (Cascading Style Sheets) is used for website design and layout. Together, these languages form the foundation of the World Wide Web. They are the basis of what one needs to know to create useful and well-designed websites, and to read the source code of existing websites and website templates. This workshop walks participants through the fundamentals of HTML and CSS. The purpose of this unit is to help participants understand the rudiments of making websites, with the intention of providing a strong base of knowledge from which to imagine web-based digital humanities projects."
 - date: 2026-01-22
   time: 9:00 
   title: "Introduction to Python"
   workshop: python
   description: "Python is a general-purpose programming language suitable for a wide variety of tasks in the digital humanities. Learning Python fundamentals is a gateway to analyzing data, creating visualizations, composing interactive websites, scraping the internet, and engaging in the distant reading of texts. This workshop first introduces participants to core programming concepts such as data types, variables, and functions. Participants will then learn about basic control flow by writing small programs with loops and conditional statements. They will also learn to problem solve, and practice searching for answers and debugging scripts. The workshop wraps up by exposing participants to intermediate tools for further exploration."
 - date: 2026-01-22
   time: 12:30 
   title: "Data Manipulation in Pandas & Jupyter Notebooks"
   workshop: pandas
   description: "Python is a general-purpose programming language suitable for a wide variety of tasks in the digital humanities. Learning Python fundamentals is a gateway to analyzing data, creating visualizations, composing interactive websites, scraping the internet, and engaging in the distant reading of texts. This workshop first introduces participants to core programming concepts such as data types, variables, and functions. Participants will then learn about basic control flow by writing small programs with loops and conditional statements. They will also learn to problem solve, and practice searching for answers and debugging scripts. The workshop wraps up by exposing participants to intermediate tools for further exploration."
 - date: 2026-01-23
   time: 9:00 
   title: "Track A: Data Manipulation in Pandas & Jupyter Notebooks"
   workshop: pandas
   description: "Python is a general-purpose programming language suitable for a wide variety of tasks in the digital humanities. Learning Python fundamentals is a gateway to analyzing data, creating visualizations, composing interactive websites, scraping the internet, and engaging in the distant reading of texts. This workshop first introduces participants to core programming concepts such as data types, variables, and functions. Participants will then learn about basic control flow by writing small programs with loops and conditional statements. They will also learn to problem solve, and practice searching for answers and debugging scripts. The workshop wraps up by exposing participants to intermediate tools for further exploration."
 - date: 2026-01-23
   time: 10:15 
   title: "Track A: Text Analysis with Python"
   workshop: text-analysis
   description: "Analyzing textual data opens a new way to interrogate the world. Put simply, it is a way to 'read' and interpret the incredible amount of text generated past and present. This workshop will introduce techniques that can help you get a handle on textual data, turn qualitative texts into quantitative objects. We will be using the Natural Language Toolkit (NLTK) package in Python and thinking through how to clean data and start using our analytical muscles to conceptualize and operationalize this textual data."
 - date: 2026-01-23
   time: 9:00 
   title: "Track B: Introduction to Mapping with QGIS"
   description: "In this workshop, you will learn About the basics of making digital maps using the open access tool QGIS. You will learn about points, polygons, vectors, and how to create layers of detail."
